// <auto-generated />
namespace WendingMechine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Nothing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nothing));
        
        string IMigrationMetadata.Id
        {
            get { return "201912181729446_Nothing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
